✅ Pull-to-Refresh implementation
iqfareez/iium_schedule pull request #51
Opened 2022-10-27 01:42 UTC by ElyasAsmad

# Description

Refreshes the schedule data from _schedule1.php_

Fixes #50 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

2022-10-27 20:30 UTC, iqfareez reviewed
Salam. Thank you for this very nice addition!! 😄 I always wanted to add this feature but couldn't find time to do it.

Suggestion: Skip update subject where venue is empty. For example, in my cases, my lab venue in imaalum is blank. The lecturer update abt the venue through ms teams etc, so I updated manually in the schedule. With this update, seems like it can override my previously set schedule.

2022-10-27 20:30 UTC, iqfareez commented on lib/views/saved_schedule/saved_schedule_layout.dart
> +    widget._box.put(scheduleIdx, currentSchedule);
Can be replaced with 
```
currentSchedule.save();
```

2022-10-28 06:36 UTC, ElyasAsmad commented on lib/views/saved_schedule/saved_schedule_layout.dart
> +    }).toList();
Hello Iqmal,

Regarding the random colour thing, actually I was having some problem while updating the Hive object, as the new fetched data overrides the previous colour used, causing the app to crash as the colour value is null (refer https://github.com/iqfareez/iium_schedule/issues/50#issuecomment-1293314349).

Anyways, I will try to find a workaround for this matter. 😎👍🏻

2022-10-29 02:26 UTC, ElyasAsmad commented on lib/views/saved_schedule/saved_schedule_layout.dart
> +    final kuliyyah = name.split(' ').elementAt(0);
I will try to implement the feature to save kuliyyah into HiveDB. New commit will be submitted afterwards.

2022-10-30 00:34 UTC, iqfareez requested changes

2022-10-30 00:34 UTC, iqfareez commented on lib/views/saved_schedule/saved_schedule_layout.dart
> +      if (updatedSubject.venue == '') return prevSubject;
```suggestion
      if (updatedSubject.venue == null) return prevSubject;
```
Checking if the string is empty doesn't guarantee the venue is empty. I think checking for null is better, in-line with the albiruni implementation:

https://github.com/iqfareez/albiruni/blob/b8c561eb33ca71625b231bcb3fab993ed64a8952/lib/src/albiruni_base.dart#L152

2022-10-30 00:40 UTC, iqfareez commented on lib/views/saved_schedule/saved_schedule_layout.dart
> +    }).toList();
Nice works. Seems like the random colour thingy has been resolved., right?

2022-10-30 19:07 UTC, ElyasAsmad commented
Hello @iqfareez !

In these commits, I have added support for HiveDB to save student's kuliyyah and regenerated Hive's adapter files for this project.

For the #51 feature, I have updated the `onRefresh` method to use the data from HiveDB instead of using the hardcoded kuliyyah information in the schedule title (which is very unsafe).

2022-10-30 19:12 UTC, ElyasAsmad commented on lib/views/saved_schedule/saved_schedule_layout.dart
> +    }).toList();
Yep! 

[099032d](https://github.com/iqfareez/iium_schedule/pull/51/commits/099032d1813252fb7a0a78176c3d15c2c8e2b518)

2022-10-30 19:26 UTC, ElyasAsmad commented on lib/views/saved_schedule/saved_schedule_layout.dart
> +      if (updatedSubject.venue == '') return prevSubject;
Fixed the code, thanks for the new knowledge!

2022-10-31 08:10 UTC, iqfareez commented on lib/views/saved_schedule/saved_schedule_layout.dart
> +      if (updatedSubject.venue == '') return prevSubject;
No problem

2022-10-31 13:41 UTC, iqfareez approved these changes
lgtm!

![You've Got LGTM](https://media.giphy.com/media/W7K4C2BnqqafLhHwpX/giphy.gif)

However, before merging this PR, I'm gonna work with #47 first.

2022-10-31 13:45 UTC, iqfareez commented
@all-contributors add @ElyasAsmad  for code

2022-11-09 07:39 UTC, merged

2022-11-09 07:42 UTC, iqfareez commented
Hrp jadi. @all-contributors add @ElyasAsmad for code